version: "3.9"
services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    networks:
      traefik:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${STATIC_PATH}:/www/data:ro
      - nginx:/var/log/nginx
    labels:
      - traefik.enable=true

      - traefik.http.routers.nginxMain.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxMain.service=nginxMain
      - traefik.http.routers.nginxMain.entryPoints=http

      - traefik.http.routers.nginxMainHttps.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxMainHttps.service=nginxMain
      - traefik.http.routers.nginxMainHttps.entryPoints=https
      - traefik.http.routers.nginxMainHttps.tls.certResolver=letsEncrypt

      - traefik.http.services.nginxMain.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  nginx: