name: 'Deploy'

on:
  push:
    branches:
      - main

env:
  HOST: treeton.org

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Build
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - run: |
          yarn install
          yarn build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          source: docker,docker-compose.yaml,.env.prod,dist
          target: /srv/${{ github.repository }}
          overwrite: true

      - name: Docker compose up
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: |
            cd /srv/${{ github.repository }}
            docker compose --env-file .env.prod pull
            docker compose --env-file .env.prod down
            docker compose --env-file .env.prod up -d
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
